// Code generated by swagger-doc. DO NOT EDIT.

package v1alpha1

func (NodeConfig) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "NodeConfig something something else\n\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+genclient",
	}
}

func (NodeConfigSpec) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (NodeConfigStatus) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (NodeConfigList) SwaggerDoc() map[string]string {
	return map[string]string{
		"":      "+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
		"items": "+listType=atomic",
	}
}
