// Code generated by swagger-doc. DO NOT EDIT.

package v1alpha1

func (NodeConfig) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "NodeConfig represents a subset of Node resources that we want to expose\nto virtual machines.\n\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+genclient",
	}
}

func (NodeConfigSpec) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (USB) SwaggerDoc() map[string]string {
	return map[string]string{
		"usbHostDevices": "+listType=atomic",
	}
}

func (USBHostDevices) SwaggerDoc() map[string]string {
	return map[string]string{
		"usbVendorSelector": "This is the selector for the USB device. To identify a USB device in a node, the minimum\nnecessary is its vendor:product information. As we could have multiple devices with the\nsame vendor:product information, a few other optional informations can be used to select the\ndevice, by using either serial number or specifying device's Bus and Device Number:\nMinimal example: \"0951:1666\"\nWith serial number: \"0951:1666,serial=E0D55E6CBD23E691583A004D\"\nWith bus and device number: \"0951:1666,bus=2,device=4\"",
	}
}

func (NodeConfigStatus) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (NodeConfigList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
	}
}
