// Code generated by swagger-doc. DO NOT EDIT.

package v1alpha1

func (NodeConfig) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "NodeConfig represents a subset of Node resources that we want to expose\nto virtual machines.\n\n+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object\n+genclient",
	}
}

func (NodeConfigSpec) SwaggerDoc() map[string]string {
	return map[string]string{
		"usb": "+listType=atomic",
	}
}

func (USB) SwaggerDoc() map[string]string {
	return map[string]string{
		"resourceName":   "The resource name which identifies the list of USB host devices.\ne.g: kubevirt.io/storage for generic storages or kubevirt.io/bootable-usb",
		"usbHostDevices": "+listType=atomic",
	}
}

func (USBHostDevices) SwaggerDoc() map[string]string {
	return map[string]string{
		"selectByVendorProduct": "The vendor:product of the devices we want to select.\ne.g: \"0951:1666\"",
	}
}

func (NodeConfigStatus) SwaggerDoc() map[string]string {
	return map[string]string{}
}

func (NodeConfigList) SwaggerDoc() map[string]string {
	return map[string]string{
		"": "+k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object",
	}
}
