apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.kubevirt.io: ""
  name: kubevirts.kubevirt.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: kubevirt.io
  names:
    categories:
    - all
    kind: KubeVirt
    plural: kubevirts
    shortNames:
    - kv
    - kvs
    singular: kubevirt
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha3
  versions:
  - name: v1alpha3
    served: true
    storage: true
  "validation":
    "openAPIV3Schema":
      description: KubeVirt represents the object deploying all KubeVirt resources
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            imagePullPolicy:
              description: The ImagePullPolicy to use.
              type: string
            imageRegistry:
              description: The image registry to pull the container images from Defaults
                to the same registry the operator's container image is pulled from.
              type: string
            imageTag:
              description: The image tag to use for the continer images installed.
                Defaults to the same tag as the operator's container image.
              type: string
            monitorAccount:
              description: The name of the Prometheus service account that needs read-access
                to KubeVirt endpoints Defaults to prometheus-k8s
              type: string
            monitorNamespace:
              description: The namespace Prometheus is deployed in Defaults to openshift-monitor
              type: string
            uninstallStrategy:
              description: Specifies if kubevirt can be deleted if workloads are still
                present. This is mainly a precaution to avoid accidental data loss
              type: string
        status:
          description: KubeVirtStatus represents information pertaining to a KubeVirt
            deployment.
          type: object
          properties:
            conditions:
              type: array
              items:
                description: KubeVirtCondition represents a condition of a KubeVirt
                  deployment
                type: object
                properties:
                  lastProbeTime:
                    type: string
                    format: date-time
                    nullable: true
                  lastTransitionTime:
                    type: string
                    format: date-time
                    nullable: true
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
            observedDeploymentConfig:
              type: string
            observedDeploymentID:
              type: string
            observedKubeVirtRegistry:
              type: string
            observedKubeVirtVersion:
              type: string
            operatorVersion:
              type: string
            phase:
              description: KubeVirtPhase is a label for the phase of a KubeVirt deployment
                at the current time.
              type: string
            targetDeploymentConfig:
              type: string
            targetDeploymentID:
              type: string
            targetKubeVirtRegistry:
              type: string
            targetKubeVirtVersion:
              type: string
